name: Generate Release Assets

on:
  release:
    types: [published]

permissions:
  actions: write
  contents: write

jobs:
  tarball:
    name: Create and Upload Tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Tarball
        run: ./make-dist.sh ${{ github.ref_name }} | tee /dev/stdout > TARBALL_NAME
      # Since this is all within the same job, could just load the tarball name
      # directly from TARBALL_NAME file, keeping it using GITHUB_ENV so I have
      # a future reference.
      #
      # NOTE: DO NOT QUOTE VALUES SENT TO $GITHUB_ENV! it will read the quotes
      # as part of the value.
      - name: Load Tarball Name
        run: echo "TARBALL_NAME=$(cat TARBALL_NAME)" >> $GITHUB_ENV
      - name: Verify Files
        run: ls -la
      - name: Upload To Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release upload ${{ github.ref_name }} "$TARBALL_NAME"
